@startuml SP3

:User: --> (User chooses search in menu)
(User chooses search in menu) --> (User writes the name of a movie)
(User writes the name of a movie) --> (all information about the movie is shown to the user)
(all information about the movie is shown to the user) --> (the movie menu shows your options)
(the movie menu shows your options) --> (User chooses to add the movie to liked list)
@enduml